### ISSUE TITLE
Solution to gulper failing in node 6.2 and above

### ISSUE THREAD

**Issue by mujuni88** [anatoo/gulper#7]
I forked a fix from @willhoag and created a release v0.2.0. 

`npm i -g https://github.com/mujuni88/gulper/archive/v0.2.0.tar.gz`.

**Comment by mikila85** [comment]
not working on 6.3.1
any fix for this or the gulper is dead?

**Comment by anatoo** [comment]
Fixed.

**Comment by mikila85** [comment]
still getting same error after reinstalling greater

C:\Users\mike\AppData\Roaming\npm\node_modules\gulper\node_modules\node-dev\lib\index.js:119
  var i = mod.lastIndexOf(n)
              ^

TypeError: mod.lastIndexOf is not a function
    at getPrefix (C:\Users\mike\AppData\Roaming\npm\node_modules\gulper\node_modules\node-dev\lib\index.js:119:15)
    at getLevel (C:\Users\mike\AppData\Roaming\npm\node_modules\gulper\node_modules\node-dev\lib\index.js:109:11)
    at C:\Users\mike\AppData\Roaming\npm\node_modules\gulper\node_modules\node-dev\lib\index.js:76:44
    at ChildProcess.handleMessage (C:\Users\mike\AppData\Roaming\npm\node_modules\gulper\node_modules\node-dev\lib\ipc.js:19:43)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by anatoo** [comment]
@mikila85 I fixed on master branch and does not release new version yet. Wait a moment until release.
